// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Topic struct {
	TopicID   int64              `json:"topic_id"`
	UserID    int64              `json:"user_id"`
	Title     string             `json:"title"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
}
