// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"
)

const findTopicByID = `-- name: FindTopicByID :one
SELECT topic_id, user_id, title, created_at FROM Topics WHERE topic_id = $1
`

func (q *Queries) FindTopicByID(ctx context.Context, topicID int64) (Topic, error) {
	row := q.db.QueryRow(ctx, findTopicByID, topicID)
	var i Topic
	err := row.Scan(
		&i.TopicID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const listTopics = `-- name: ListTopics :many
SELECT topic_id, user_id, title, created_at FROM Topics ORDER BY title
`

func (q *Queries) ListTopics(ctx context.Context) ([]Topic, error) {
	rows, err := q.db.Query(ctx, listTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Topic
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.TopicID,
			&i.UserID,
			&i.Title,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
